repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # or latest
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0   # or latest
    hooks:
      - id: flake8
